Add 3 Letter Country Codes
chancejs/chancejs pull request #576
Opened 2023-03-15 14:03 UTC by nicballesteros

Allows a user to request a 3-letter country code.
`chance.country({ alpha3: true })`

2023-03-15 21:16 UTC, somejeff requested changes
There some formatting side effects in the test.  Can you restore it so that only lines 182-187 are affected?

2023-03-15 21:17 UTC, nicballesteros commented
Let me do that. It just the way my IDE is set up. It removes whitespace.

2023-03-15 21:30 UTC, nicballesteros commented
@somejeff I fixed it. Thanks for the reply.

2023-05-10 05:43 UTC, leesei commented
On the topic of country codes, why not use https://github.com/chancejs/chance-iso3166?
Externing it will reduce the file size of `chance.js` and have better modularization?

2023-08-21 08:45 UTC, AbdullahWins approved these changes
good job

2025-05-18 19:17 UTC, closed without merging